from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.mail import send_mail
from django.conf import settings
from .models import Lead

@receiver(post_save, sender=Lead)
def send_lead_notification(sender, instance, created, **kwargs):
    if created:
        subject = f"New Enquiry from {instance.name}"
        message = f"""
        New enquiry received from Datawizable website:

        Name: {instance.name}
        Email: {instance.email}
        Company: {instance.company}
        Industry: {instance.industry.name if instance.industry else 'N/A'}

        Message:
        {instance.message}

        ---
        This email was automatically generated by the Datawizable Digital Business Platform.
        """

        try:
            send_mail(
                subject,
                message,
                settings.DEFAULT_FROM_EMAIL,
                [settings.NOTIFICATION_EMAIL],
                fail_silently=False,
            )
        except Exception as e:
            # In production, we should log this error properly
            print(f"Error sending email: {e}")
