# Generated by Django 6.0.6 on 2026-06-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(max_length=200)),
                ('service_interest', models.CharField(choices=[('DT', 'Digital Transformation'), ('BA', 'Business Automation'), ('AI', 'AI Integration'), ('CP', 'Custom Platforms'), ('DI', 'Decision Intelligence'), ('CB', 'Capacity Building')], max_length=2)),
                ('country', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=100)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('challenge_description', models.TextField(help_text='What is slowing your organization down?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
            ],
        ),
    ]
